main:
  - name: "Startsiden"
    url: "/"
    weight: 1

  - name: "Om oss"
    url: "/omoss"
    weight: 2

  - name: "Infosider"
    url: "/info"
    weight: 4

  - name: "Styrets arbeid"
    url: "/styret"
    weight: 5

buttons:
  - name: "HÃ¸yhotellet"
    url: "/hoyhotellet"
    weight: 6

