description: "Foreningen Midtskogen Vel verner og ivaretek friluftsomådet Midtskogen i Os sentrum. Friområdet er ein grøn lunge midt i nabolaget og ein lågterskel møteplass for born, ungdom og vaksne. Her kan ein leika, spela ball, ta ein prat over gjerdet – eller berre pusta ut. Slik bidreg området til trivsel, helse og tryggleik i kvardagen.."

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"


